### ISSUE TITLE
M365-Toolbox Build

### ISSUE THREAD

**Issue by achaouki** [lanrat/m365-toolbox#1]
Hello Lanrat

Could you please send me the APK file of the M365-Toolbox

my email : chaoukiaminos@gmail.com

Thanks in advance 👍

**Comment by lanrat** [comment]
The project is open source. You can compile the source code yourself to generate the APK.

Opening this project in Android Studio should make this easy.

**Comment by achaouki** [comment]
Please i can't build the APK , i install android studio but in build option i can't find the generate apk !

Help please !! My M365 id locked and i need the pass to unlock it ! 

HELP !
